name: 'crop_project'
version: '1.0.0'

profile: 'crop_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  crop_live:
    +materialized: table
  facts:
    +materialized: table
  dimensions:
    +materialized: table
  staging:
    +materialized: table
  intermediate:
    +materialized: table
