version: 2
sources:
  - name: crop_data
    database: dbt-crop
    schema: crop_weather_ds
    tables:
      - name: crop_weather

models:
  - name: crop  # must match crop.sql
    description: "Crop production records from 2018 onwards"
    columns:
      - name: state
        description: "State where crop was grown"
        tests:
          - not_null
      - name: crop
        description: "Crop name"
      - name: year
        description: "Crop year (renamed from crop_year)"
      - name: production
        description: "Amount of crop produced"
